### ISSUE TITLE
[REQUEST] Text/Resource editing

### ISSUE THREAD

**Issue by DropsMJay** [Jayveer/Gcx#1]
Hello, the text/resources inside scenerio.gcx from MGS3 can be edited like normal text? It looks like some binary data is between the text.

Thanks and keep up the good work.

**Comment by Jayveer** [comment]
That would require writing a compiler from GCL to GCX, which I might do one day, but I don't have much motivation to do so.

**Comment by DropsMJay** [comment]
I understand. Thank you.
